services:
  app_db:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Password1
      POSTGRES_DB: mydatabase
    networks:
      - dotnet_app_network
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  dotnet_app_network:
    external: true

volumes:
  pgdata:
    name: pgdata
